# 工作流名称
name: Generate Snake

# 工作流触发时机
on:
  push:
    branches: 
      - main  
  schedule:
    - cron:  "0 0 * * *" 

# 作业
jobs:
  # 生成统计图
  github-metrics: 
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate metrics-Half-year-calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          filename: assets/metrics.plugin.isocalendar.svg
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

  # 生成 Snake 图(贪吃蛇)
  github-Snake: 
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/github-snake.svg
            assets/github-snake-dark.svg?palette=github-dark
            assets/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
      
      - name: Commit and Push
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add assets/github-snake.svg assets/github-snake-dark.svg assets/ocean.gif
          git commit -m "Generated GitHub Snake"
          git push
